### PR TITLE
fix "ClassNotFoundException: javax.xml.bind.JAXBException" with Java 10

### PR DESCRIPTION
**Pull request by adrienjoly**
see https://github.com/ohnosequences/sbt-s3-resolver/issues/58#issue-265609180

### CODE REVIEW

**Comment by vladgolubev** [comment]
```
A new version of the package tika-text-extract (2.2.0) was published at 2018-05-07T22:56:25.955Z from 77.1XX.XX.XX. The shasum of this package was 9341f62d2e0f166977829945a72c09b1bae2defc.
```

**Comment by vladgolubev** [comment]
@adrienjoly hey, does your fix work for you? I have the following error:

```
Unrecognized option: --add-modules=java.xml.bind,java.activation
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
error: Unrecognized option: --add-modules=java.xml.bind,java.activation
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by adrienjoly** [comment]
It did with Java v10.

What version of Java are you using, @vladgolubev?

Can you share a sample program that I can quickly execute to test on my end, please?

**Comment by vladgolubev** [comment]
@adrienjoly ah, ok then, I run this in AWS Lambda where it has Java 8 only, thanks

**Comment by adrienjoly** [comment]
I will try to run it on Java 8 to see if I can reproduce this behavior, and maybe find a fix that works with both versions.

**Comment by adrienjoly** [comment]
Ok, I'm getting the same error as you, when running my script using Java 8...

Apparently, that workaround just works with Java 9+, but it's not compatible with older version of Java... (see https://github.com/aws/aws-sdk-java/issues/1092)

Feel free to close this PR until a better solution can be found. Unfortunately, I will not spend more time on this for now, as I don't plan to use Tika yet.

**Pull request merged**
